name: TestDockerServices
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - "envs/container/docker/**"    
      - "pipelines/github-action/github-action.tests-docker.yml"
      - ".github/workflows/github-action.tests-docker.yml"      
   
  pull_request:
    branches: [ main ]
    paths:
      - "envs/container/docker/**"    
      - "pipelines/github-action/github-action.tests-docker.yml"
      - ".github/workflows/github-action.tests-docker.yml"      
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "detect-secrets"
  test-docker-av-services:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      configurationFile: 'avtool.docker.env'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Pre-requisites
        run: |
          pipelines/utils/avtool.sh -a install -c ${{ env.configurationFile }} -e true

      - name: Integration Test services 
        run: |
          pipelines/utils/avtool.sh -a integration -c ${{ env.configurationFile }} -e true

